version: '3.7'

services:
  plop:
    image: 'plop:0.0.1'
    container_name: 'plop'
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    environment: 
      API_CONFIGURATION: ${API_CONFIGURATION}
      API_PORT: ${API_PORT}
      API_HOSTNAME: ${API_HOSTNAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
    links: 
      - diplo
    depends_on: 
      - diplo

  diplo:
    image: mongo:latest
    container_name: 'diplo'
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment: 
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
    
