version: '3.7'

services:
  plop:
    image: 'plop-docker:0.0.1'
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    environment: 
      API_CONFIGURATION: ${API_CONFIGURATION}
      API_PORT: ${API_PORT}
      API_HOSTNAME: ${API_HOSTNAME}
    links:
      - diplo
    depends_on:
      - diplo

  diplo:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
